# Generated by Django 2.2.13 on 2021-10-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_reportrecord_user_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='factory_type',
            new_name='ohshown_event_type',
        )
    ]
