# Generated by Django 2.2.13 on 2022-04-23 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0040_rename_factory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OhshownEvent',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_number', models.IntegerField(unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('landcode', models.CharField(blank=True, max_length=50, null=True)),
                ('towncode', models.CharField(blank=True, max_length=50, null=True)),
                ('townname', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('sectcode', models.CharField(blank=True, max_length=50, null=True)),
                ('sectname', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('ohshown_event_type', models.CharField(blank=True, choices=[('2-1', '目擊黑熊'), ('2-2', '發現痕跡'), ('2-3', '其他')], max_length=3, null=True)),
                ('before_release', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('G', '政府'), ('U', '使用者')], default='U', max_length=1)),
                ('cet_review_status', models.CharField(choices=[('A', '尚未審查'), ('O', '已審查-不檢舉'), ('P', '已審查-需補件'), ('Q', '已審查-待檢舉'), ('X', '已審查-已生成公文')], default='A', max_length=1)),
                ('cet_report_status', models.CharField(choices=[('A', '未舉報'), ('O', '第一次發文待回覆'), ('P', '第一次發文已播電話追蹤'), ('Q', '第一次回文'), ('X', '第二次發文待回覆'), ('Y', '第二次發文已播電話追蹤'), ('Z', '第二次回文'), ('B', '已結案')], default='A', max_length=1)),
                ('building_status', models.CharField(blank=True, choices=[('A', '既有'), ('B', '新增'), ('C', '興建中'), ('D', '難以判定')], max_length=1, null=True)),
                ('usage_status', models.CharField(blank=True, choices=[('A', '低污染產業'), ('B', '高污染產業'), ('C', '其他用途'), ('D', '難以判定')], max_length=1, null=True)),
                ('highlight_category', models.CharField(blank=True, choices=[('A', '新廠商寄居'), ('B', '倉儲'), ('C', '擴建')], max_length=1, null=True)),
                ('status_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cet_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ohshown Event',
                'verbose_name_plural': 'Ohshown Events',
            },
        ),
        migrations.RemoveField(
            model_name='factory',
            name='cet_reviewer',
        ),
        migrations.DeleteModel(
            name='RecycledFactory',
        ),
        migrations.AlterField(
            model_name='document',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.OhshownEvent'),
        ),
        migrations.AlterField(
            model_name='image',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.OhshownEvent'),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_records', to='api.OhshownEvent'),
        ),
        migrations.AlterField(
            model_name='review',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.OhshownEvent'),
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
        migrations.CreateModel(
            name='RecycledOhshownEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.ohshownevent',),
            managers=[
                ('recycle_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
