# Generated by Django 2.2.13 on 2021-10-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_factory_type'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_factory RENAME TO api_ohshownevent;"
        )
    ]
