# Generated by Django 2.2.13 on 2022-04-24 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohshownevent',
            name='sight_see_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
