# Generated by Django 2.2.13 on 2022-06-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_ohshownevent_sight_see_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohshownevent',
            name='sight_see_date_time',
            field=models.DateTimeField(),
        ),
    ]
