# Generated by Django 2.2.13 on 2022-06-07 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220607_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootprintForm',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(0, '糞便'), (1, '腳印'), (2, '爪痕'), (3, '食痕'), (4, '其他')], null=True)),
                ('type_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, '新'), (1, '舊'), (2, '不清楚')])),
                ('status_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('image_uploaded', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
