# Generated by Django 2.2.13 on 2022-07-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_bear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, help_text='聯絡者姓名', max_length=50, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='聯絡電話', max_length=15, null=True)),
                ('contact_mail', models.EmailField(blank=True, help_text='聯絡信箱', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
