# Generated by Django 2.2.13 on 2022-07-07 06:57

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShownForm',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ohshown_feeling', models.CharField(blank=True, help_text='看到熊當下，目擊者的感覺', max_length=255, null=True)),
                ('human_number', models.IntegerField(blank=True, help_text='目擊熊當下人數', null=True)),
                ('human_behavior', models.IntegerField(blank=True, choices=[(0, '行進'), (1, '休息'), (2, '開車'), (3, '煮食/用餐'), (4, '工作'), (5, '其他')], help_text='目擊當下目擊者在做什麼', null=True)),
                ('human_behavior_text', models.CharField(blank=True, help_text='目擊當下目擊者在做什麼-文字補充', max_length=255, null=True)),
                ('distance', models.IntegerField(blank=True, choices=[(0, '小於20'), (1, '20-50'), (2, '50-100'), (3, '大於100公尺')], help_text='目擊者與熊之間的距離', null=True)),
                ('bear_behavior', models.IntegerField(blank=True, choices=[(0, '慢步'), (1, '奔跑'), (2, '爬樹'), (3, '休息'), (4, '覓食'), (5, '其他')], help_text='目擊當下熊在做什麼', null=True)),
                ('bear_behavior_text', models.CharField(blank=True, help_text='目擊當下熊在做什麼-文字補充', max_length=255, null=True)),
                ('food', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, '不清楚'), (1, '果實'), (2, '莖葉'), (3, '蜂蜜'), (4, '昆蟲'), (5, '動物'), (6, '垃圾/廚餘'), (7, '家禽/畜'), (8, '動物飼料'), (9, '農作物'), (10, '其他')], help_text='黑熊在吃什麼', null=True), size=None)),
                ('food_object', django.contrib.postgres.fields.jsonb.JSONField()),
                ('bear_notice', models.IntegerField(blank=True, choices=[(0, '黑熊一直未發現我'), (1, '目擊前黑熊就發現我了'), (2, '目擊後約X分鐘黑熊發現我的存在')], help_text='黑熊何時注意到人員存在', null=True)),
                ('bear_notice_minutes', models.IntegerField(blank=True, help_text='目擊後約X分鐘黑熊發現人員存在-X數字', null=True)),
                ('human_reaction', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, '靜止不動'), (1, '緩慢離開'), (2, '快速逃跑'), (3, '爬樹'), (4, '使用防熊噴霧'), (5, '大聲喊叫或發出聲響'), (6, '趴在地上裝死'), (7, '拿可防身物品威嚇'), (8, '其他')], help_text='目擊黑熊後，目擊者反應', null=True), size=None)),
                ('human_reaction_text', models.CharField(blank=True, help_text='目擊黑熊後，目擊者反應-文字補充', max_length=255, null=True)),
                ('bear_reaction', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, '繼續原先的活動'), (1, '緩慢走開'), (2, '吼叫威嚇'), (3, '站立'), (4, '朝人觀望、戒備'), (5, '快速逃離'), (6, '主動接近人'), (7, '其它')], help_text='黑熊發現目擊者後，黑熊的反應', null=True), size=None)),
                ('bear_reaction_text', models.CharField(blank=True, help_text='黑熊發現目擊者後，黑熊的反應-文字補充', max_length=255, null=True)),
                ('human_hurt', models.BooleanField(default=False, help_text='是否有人受傷或意外發生')),
                ('human_hurt_text', models.CharField(blank=True, help_text='是否有人受傷或意外發生-文字補充', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
